---
- name: Ensure acl package is installed (for setfacl)
  apt:
    name: acl
    state: present
    update_cache: true

- name: Copy database configuration
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: '0644'

- name: Copy user access configuration
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0640'
  notify: restart postgresql

- name: Create PostgreSQL user
  postgresql_user:
    state: present
    name: "{{ postgres_user }}"
    password: "{{ postgres_password }}"
  become: true
  become_user: postgres

